/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Accordion: typeof import('./src/components/molecules/Accordion/Accordion.vue')['default']
    BackgroundBreadcrumb: typeof import('./src/components/molecules/BackgroundBreadcrumb/BackgroundBreadcrumb.vue')['default']
    Breadcrumb: typeof import('./src/components/atoms/Breadcrumb/Breadcrumb.vue')['default']
    Card: typeof import('./src/components/molecules/Card/Card.vue')['default']
    CheckBox: typeof import('./src/components/atoms/Checkbox/CheckBox.vue')['default']
    DatetimeInput: typeof import('./src/components/atoms/DatetimeInput/DatetimeInput.vue')['default']
    Footer: typeof import('./src/components/layouts/Footer/Footer.vue')['default']
    Header: typeof import('./src/components/layouts/Header/Header.vue')['default']
    ImageGallery: typeof import('./src/components/molecules/ImageGallery/ImageGallery.vue')['default']
    Input: typeof import('./src/components/atoms/Input/Input.vue')['default']
    IntroCategoryBox: typeof import('./src/components/molecules/IntroCategoryBox/IntroCategoryBox.vue')['default']
    Loader: typeof import('./src/components/atoms/Loader/Loader.vue')['default']
    MobileMenu: typeof import('./src/components/layouts/MobileMenu/MobileMenu.vue')['default']
    MobileSidebarMenu: typeof import('./src/components/layouts/MobileSidebarMenu/MobileSidebarMenu.vue')['default']
    Navbar: typeof import('./src/components/layouts/Navbar/Navbar.vue')['default']
    OrderSummary: typeof import('./src/components/molecules/OrderSummary/OrderSummary.vue')['default']
    ProfileMenu: typeof import('./src/components/molecules/ProfileMenu/ProfileMenu.vue')['default']
    Rating: typeof import('./src/components/atoms/Rating/Rating.vue')['default']
    RButton: typeof import('./src/components/atoms/RButton/RButton.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    RowCard: typeof import('./src/components/molecules/RowCard/RowCard.vue')['default']
    SectionBox: typeof import('./src/components/molecules/SectionBox/SectionBox.vue')['default']
    Select: typeof import('./src/components/atoms/Select/Select.vue')['default']
    ServiceCard: typeof import('./src/components/molecules/ServiceCard/ServiceCard.vue')['default']
    VanActionBar: typeof import('vant/es')['ActionBar']
    VanActionBarButton: typeof import('vant/es')['ActionBarButton']
    VanActionBarIcon: typeof import('vant/es')['ActionBarIcon']
    VanButton: typeof import('vant/es')['Button']
    VanCollapse: typeof import('vant/es')['Collapse']
    VanCollapseItem: typeof import('vant/es')['CollapseItem']
    VanConfigProvider: typeof import('vant/es')['ConfigProvider']
    VanIcon: typeof import('vant/es')['Icon']
    WishlistProductCard: typeof import('./src/components/molecules/WishlistProductCard/WishlistProductCard.vue')['default']
  }
}
